stages:
  download:
    cmd: python src/download_data.py
    outs:
      - data/raw/raw.csv

  preprocess:
    cmd: python src/preprocess_data.py
    deps:
      - data/raw/raw.csv
    outs:
      - data/processed/train_data.csv
      - data/processed/test_data.csv

  train:
    cmd: python src/train_model.py
    deps:
      - data/processed/train_data.csv
    outs:
      - models/model.pkl

  evaluate:
    cmd: python src/evaluate_model.py
    deps:
      - data/processed/test_data.csv
      - models/model.pkl
    metrics:
      - metrics/metrics.json